### PR TITLE
docs: refine documentation of halo:comment tag

### PR DESCRIPTION
**Pull request by ruibaby**
从 Halo 2.9 开始，判断评论组件是否显示的条件不再只是单纯的判断评论插件是否安装。

see https://github.com/halo-dev/halo/pull/4271

/kind documentation

```release-note
None
```

### CODE REVIEW

**Review by guqing — COMMENTED** [review]
/lgtm

**Comment by ruibaby** [comment]
/hold 

等待 https://github.com/halo-dev/docs/pull/283 合并。

**Comment by JohnNiang** [comment]
Hi @ruibaby , PR https://github.com/halo-dev/docs/pull/283 has been merged.

**Review by JohnNiang — APPROVED** [review]
/approve

**Pull request merged**
